{
 "title": "Salesforce Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "SCM Link",
   "type": "text",
   "description": "Source Code Management repository.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "Update link here for your SCM repo."
   }
  },
  { "title": "Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Salesforce Incidents",
   "type": "gauge",
   "description": "The # of open incidents against each Salesforce org.",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(salesforce_incidents[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salesforce Incidents Over Time",
   "type": "timeseries",
   "description": "The # of open incidents against each Salesforce org over time.",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(salesforce_incidents[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incidents details",
   "type": "table",
   "description": "Incidents details against each Salesforce org.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(pod, severity, message) (max_over_time(salesforce_incidents[30m]))"
    }
   ]
  },
  { "title": "API Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Salesforce API Usage % (Data refreshes every 30 minutes)",
   "type": "gauge",
   "description": "The usage percentage for each API.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(limit_name) (max_over_time(salesforce_api_usage_percentage[30m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salesforce API Usage % (Data refreshes every 30 minutes)",
   "type": "timeseries",
   "description": "API limits in Salesforce refer to the maximum number of API requests that can be made to a Salesforce instance over a period of time.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(limit_name) (max_over_time(salesforce_api_usage_percentage[30m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Licenses Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "User Licenses Usage % (Data refreshes every 30 minutes)",
   "type": "timeseries",
   "description": "User licenses in Salesforce define the baseline level of features and permissions that a user can access within the Salesforce environment, determining what apps, objects, and functionalities are available to them based on their assigned license type.",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(license_name) (max_over_time(salesforce_user_licenses_usage_percentage[30m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Active Licenses Count (Used vs Total vs Percentage Utilized)",
   "type": "barchart",
   "description": "Active Licenses details, Data refreshes every 30 minutes",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(license_name) (max_over_time(salesforce_used_user_licenses{status=\"Active\"}[30m]))",
     "legendFormat": "Used : {{license_name}}"
    },
    {
     "expr": "max by(license_name) (max_over_time(salesforce_total_user_licenses{status=\"Active\"}[30m]))",
     "legendFormat": "Total : {{license_name}}"
    },
    {
     "expr": "max by(license_name) (max_over_time(salesforce_user_licenses_usage_percentage{status=\"Active\"}[30m]))",
     "legendFormat": "Total : {{license_name}}"
    }
   ]
  },
  {
   "title": "Usage based entitlements Usage % (Data refreshes every 30 minutes)",
   "type": "timeseries",
   "description": "Usage-based entitlements licenses in Salesforce are licenses that track and limit the consumption of specific features or services based on usage metrics, such as API calls or storage, rather than per-user allocations.",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(license_name) (max_over_time(salesforce_percent_used_usage_based_entitlements[30m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage based entitlements Licenses Count(Used vs Total)",
   "type": "barchart",
   "description": "Usage based entitlements Licenses details, Data refreshes every 30 minutes",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(license_name) (max_over_time(salesforce_used_licenses_usage_based_entitlements[30m])) > 0",
     "legendFormat": "Used : {{license_name}}"
    },
    {
     "expr": "max by(license_name) (max_over_time(salesforce_total_licenses_usage_based_entitlements[30m]))",
     "legendFormat": "Total : {{license_name}}"
    }
   ]
  },
  {
   "title": "Permission Set License Usage % (Data refreshes every 30mins)",
   "type": "timeseries",
   "description": "Licenses to grants access to additional features or permissions beyond the standard Salesforce license. It allows administrators to assign specific sets of permissions to users on top of their existing user license, enabling more granular control over feature access and customization.",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(license_name) (max_over_time(salesforce_permissionset_license_usage_percentage[30m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Permissionset Licenses Count (Used vs Total)",
   "type": "barchart",
   "description": "Permissionset Active Licenses details, Data refreshes every 30 minutes",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(license_name) (max_over_time(salesforce_used_permissionset_licenses{status=\"Active\"}[30m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(license_name) (max_over_time(salesforce_total_permissionset_licenses{status=\"Active\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asynchronous Apex Jobs status by Job Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "max by(job_type) (max_over_time(salesforce_async_job_status_count[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Jobs status",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(status) (max_over_time(salesforce_async_job_status_count[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Jobs status by Method",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "max by(method) (max_over_time(salesforce_async_job_status_count[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Jobs status by Method and Status",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "max by(method, status) (max_over_time(salesforce_async_job_status_count[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Run Time (Last 1hour) by Entry Point",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg without(job, instance) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E\"}[60m]))",
       "legendFormat": "{{entry_point}}"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Run Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex Run Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Run Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Run Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex CPU Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex CPU Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex CPU Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex CPU Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Execution Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex Execution Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Execution Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Execution Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Database Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex Database Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Database Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Database Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Callout Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex CalloutTime (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Callout Time (Last 1hour) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Callout Time (Last 1hour) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Synchronous Apex Execution Time details",
     "type": "barchart",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[30m])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Execution Time details",
     "type": "barchart",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[30m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[30m])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apex exceptions occurred in last 1hour",
     "type": "stat",
     "description": "Refers to the errors that occur during the execution of Apex code",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (exception_category) (max_over_time(apex_exception_category_count[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Apex exceptions occurred in last 1hour",
     "type": "timeseries",
     "description": "Data categorized based on Types of exceptions occurred in last 1hour",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (exception_category) (max_over_time(apex_exception_category_count[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Apex CPU Timeout exception details",
     "type": "table",
     "description": "Details displayed based on CPU Timeout exceptions occurred in last 1hour",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "max by (exception_category, exception_type, exception_message, stack_trace) (max_over_time(apex_exception_details{exception_message=~\".*Apex CPU time limit exceeded.*\"}[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Apex Row Lock exception details",
     "type": "table",
     "description": "Details displayed based on Row Lock errors occurred in last 1hour",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "max by (exception_category, exception_type, exception_message, stack_trace) (max_over_time(apex_exception_details{exception_message=~\".*UNABLE_TO_LOCK_ROW.*\"}[30m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Login, EPT, Geolocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(salesforce_login_failure_total{})",
       "legendFormat": "Login Failures"
      }
     ]
    },
    {
     "title": "Experienced Page Time (EPT)",
     "type": "timeseries",
     "description": "Experienced Page Time (EPT) for 'LightningPageView'.",
     "gridPos": { "h": 16, "w": 20, "x": 4, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "salesforce_experienced_page_time{PAGE_APP_NAME='LightningSales'} and {PAGE_ENTITY_TYPE='Account'}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(salesforce_login_success_total{})",
       "legendFormat": "Login Successes"
      }
     ]
    },
    {
     "title": "Users Geolocation",
     "type": "geomap",
     "description": "User location based on their login coordinates",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "user_location", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(deployment_details{status=\"Succeeded\"}) or vector(0)\r\n",
       "legendFormat": "Successful Deployments"
      }
     ]
    },
    {
     "title": "Average Deployment Time vs Average Pending Time",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 15, "x": 4, "y": 107 },
     "targets": [
      {
       "expr": "avg(avg_over_time(deployment_pending_time[30m]))",
       "legendFormat": "Avg Deployment Pending Time"
      },
      {
       "expr": "avg(avg_over_time(deployment_time[30m]))",
       "legendFormat": "Avg Deployment Time"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(deployment_details{status=\"Failed\"}) or vector(0)",
       "legendFormat": "Failed Deployments"
      }
     ]
    }
   ]
  }
 ]
}