{
 "title": "Salesforce Production Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "interval", "query": "hourly,daily" },
   {
    "name": "page_app_name",
    "query": "LightningSalesConsole, LightningService, PSA_Project_Manager, LightningSales, Collections_Management, CAM_Lightning, Customer_Excellence, PSA_Consultant, Ava2_GoLive_Lightning, Loyalty_Lightning, all, Service, Composer, ProdlyMoover_Lightning, Avalara_Sales_Q2C, Billing_Management, ZoomClean, BETA_Avalara_Service_Support_Console, PSE_Operations, Community, Chatter, QuotetoCash_Q2C, LicenseManagementApp, Distribution_Engine, PSA_PMO, Avalara_Sales_Admin_Q2C, iSell_for_Salesforce, LinkedIn_Admin_Portal, Edit_Quotas, Partner_Order, CventLightningApp, NEO_Collections_Management, Excise_Tax_Division, Compliance, FFCentral, CSM_Lightning, QuotetoCash, OnlineSales, ZoomInfo, CameleonCPQ, SalesforceBillingConfiguration, Setup, ConnectorForce_Management, DocuSignForSalesforceCore, DocuSign_for_Salesforce_CPQ, Marketing_Operations, Activity_Management, Skilljar, Continuous, FieldPro"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: orange; text-align: center;\">\r\n    SFMon\r\n</h2>"
   }
  },
  {
   "title": "Apex Flex Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apex Flex Queue",
     "type": "stat",
     "description": "All apex jobs in a \"Holding\" status in the flex queue",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "salesforce_apex_flex_queue_sum:5m",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Apex Flex Queue Trend",
     "type": "timeseries",
     "description": "All apex jobs in a \"Holding\" status in the flex queue",
     "gridPos": { "h": 7, "w": 12, "x": 4, "y": 3 },
     "targets": [
      {
       "expr": "salesforce_apex_flex_queue_sum:5m",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incidents Over Time",
     "type": "timeseries",
     "description": "The # of open incidents against Salesforce production over time.",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(environment) (salesforce_incidents)",
       "legendFormat": "{{environment}}"
      }
     ]
    },
    {
     "title": "Incidents details",
     "type": "table",
     "description": "Displays incident details, showing only unique combinations of Severity and Incident ID. The time reflects when each combination first appeared.",
     "gridPos": { "h": 11, "w": 17, "x": 7, "y": 11 },
     "targets": [
      {
       "expr": "max by(pod, severity, environment, incident_id) (salesforce_incidents{severity!=\"ok\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "API Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 API Usage Limits",
     "type": "bargauge",
     "description": "The top API usage limits in real-time",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(max by (limit_name) (salesforce_api_usage_percentage))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Salesforce API Usage Trend",
     "type": "timeseries",
     "description": "This panel shows the percentage of API usage relative to its limit, excluding any API where usage was at 0% during the time range.",
     "gridPos": { "h": 12, "w": 16, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max by (limit_name) (salesforce_api_usage_percentage)",
       "legendFormat": "{{limit_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Licenses Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Licenses Usage % - Top 10",
     "type": "bargauge",
     "description": "User licenses in Salesforce define the baseline level of features and permissions that a user can access within the Salesforce environment, determining what apps, objects, and functionalities are available to them based on their assigned license type.",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(avg by(license_name) (avg_over_time(salesforce_user_licenses_usage_percentage[5m])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User Active Licenses Count",
     "type": "table",
     "description": "Count of total licenses and used licenses ",
     "gridPos": { "h": 11, "w": 17, "x": 7, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(license_name) (max_over_time(salesforce_used_user_licenses{status=\"Active\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(license_name) (max_over_time(salesforce_total_user_licenses{status=\"Active\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(license_name) (max_over_time(salesforce_user_licenses_usage_percentage{status=\"Active\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Usage Based Entitlements Usage % - Top 10",
     "type": "bargauge",
     "description": "Usage-based entitlements licenses in Salesforce are licenses that track and limit the consumption of specific features or services based on usage metrics, such as API calls or storage, rather than per-user allocations.",
     "gridPos": { "h": 14, "w": 7, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(max by(license_name) (max_over_time(salesforce_percent_used_usage_based_entitlements[5m])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Usage based Entitlements Licenses Count",
     "type": "table",
     "description": "Count of total licenses and used licenses",
     "gridPos": { "h": 14, "w": 17, "x": 7, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(license_name) (max_over_time(salesforce_used_licenses_usage_based_entitlements[5m]))",
       "legendFormat": "Used : {{license_name}}"
      },
      {
       "expr": "max by(license_name) (max_over_time(salesforce_total_licenses_usage_based_entitlements[5m]))",
       "legendFormat": "Total : {{license_name}}"
      },
      {
       "expr": "max by(license_name) (max_over_time(salesforce_percent_used_usage_based_entitlements[5m]))",
       "legendFormat": "Total : {{license_name}}"
      }
     ]
    },
    {
     "title": "Permission Set License Usage % - Top 15",
     "type": "bargauge",
     "description": "Licenses to grants access to additional features or permissions beyond the standard Salesforce license. It allows administrators to assign specific sets of permissions to users on top of their existing user license, enabling more granular control over feature access and customization.",
     "gridPos": { "h": 14, "w": 7, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(avg by(license_name) (avg_over_time(salesforce_permissionset_license_usage_percentage[5m])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Permissionset Licenses Count (Used vs Total)",
     "type": "table",
     "description": "Permissionset Active Licenses details",
     "gridPos": { "h": 14, "w": 17, "x": 7, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(license_name) (max_over_time(salesforce_used_permissionset_licenses{status=\"Active\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(license_name) (max_over_time(salesforce_total_permissionset_licenses{status=\"Active\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(license_name) (max_over_time(salesforce_permissionset_license_usage_percentage{status=\"Active\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Bulk API Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Bulk API Usage ($interval) by Entity Type",
     "type": "gauge",
     "description": "Displays Top 10 Bulk API usage by entity type",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "topk(5, sum by(entity_type) (${interval}_entity_type_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bulk API usage (${interval}) detail",
     "type": "table",
     "description": "Details of Top 5 Bulk API batches with respect to User ID,  Entity Type and Job ID",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "topk(5, ${interval}_bulk_api_batch_count)"
      }
     ]
    },
    {
     "title": "Bulk API usage (${interval}) detail by Entity Type",
     "type": "table",
     "description": "Details of Top 5 Bulk API batches with respect to Entity Type and User ID",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "topk(5, ${interval}_entity_type_count)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asynchronous Apex Jobs status by Job Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(job_type) (max_over_time(salesforce_async_job_status_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Jobs status",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(status) (max_over_time(salesforce_async_job_status_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Jobs status by Method",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "max by(method) (max_over_time(salesforce_async_job_status_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Jobs status by Method and Status",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "max by(method, status) (max_over_time(salesforce_async_job_status_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Run Time (Last 1hr) by Entry Point",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg without(job, instance) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E\"}[60m]))",
       "legendFormat": "{{entry_point}}"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Run Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex Run Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Run Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Run Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex CPU Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex CPU Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex CPU Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex CPU Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Execution Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex Execution Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Execution Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Execution Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Database Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex Database Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Database Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Database Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Synchronous Apex Callout Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Synchronous Apex CalloutTime (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Salesforce Asynchronous Apex Callout Time (Last 1hr) by Quiddity",
     "type": "timeseries",
     "description": "Average Salesforce Asynchronous Apex Callout Time (Last 1hr) by Quiddity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[60m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Synchronous Apex Execution Time details",
     "type": "barchart",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"V|M|R|H|I|W|L|A|E|TD\"}[5m])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Asynchronous Apex Execution Time details",
     "type": "barchart",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_run_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_cpu_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_execution_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_db_total_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[5m])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(quiddity) (avg_over_time(salesforce_apex_callout_time_seconds{quiddity=~\"F|S|Q|BA|C|K|QTXF|B\"}[5m])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EPT for Page App : $page_app_name listed by Browser",
     "type": "stat",
     "description": "Experienced Page Time (EPT) for 'LightningPageView'.",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (BROWSER_NAME) (salesforce_experienced_page_time{PAGE_APP_NAME=\"$page_app_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EPT for Page App : $page_app_name listed by Deviation reason",
     "type": "timeseries",
     "description": "Experienced Page Time (EPT) for 'LightningPageView'.",
     "gridPos": { "h": 12, "w": 9, "x": 5, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(salesforce_experienced_page_time{PAGE_APP_NAME=\"$page_app_name\"}) by (EFFECTIVE_PAGE_TIME_DEVIATION_REASON)",
       "legendFormat": "{{EFFECTIVE_PAGE_TIME_DEVIATION_REASON}}"
      }
     ]
    },
    {
     "title": "EPT for Page App : $page_app_name listed by Page APP Name",
     "type": "timeseries",
     "description": "Experienced Page Time (EPT) for 'LightningPageView'.",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (PAGE_APP_NAME) (avg_over_time(salesforce_experienced_page_time[30m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Page Time (APT) for $page_app_name",
     "type": "stat",
     "description": "The average time users spend on a specific page across all sessions",
     "gridPos": { "h": 13, "w": 5, "x": 0, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "salesforce_average_page_time{Page_name='$page_app_name'}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EPT for Page App : '$page_app_name' listed by Entity type",
     "type": "timeseries",
     "description": "Experienced Page Time (EPT) for 'LightningPageView'.",
     "gridPos": { "h": 13, "w": 19, "x": 5, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(PAGE_APP_NAME, PAGE_ENTITY_TYPE) (salesforce_experienced_page_time{PAGE_APP_NAME=\"$page_app_name\"})",
       "legendFormat": " {{PAGE_ENTITY_TYPE}}"
      }
     ]
    },
    {
     "title": "Async Apex Execution Summary",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 233 },
     "targets": [
      {
       "expr": "sum(apex_entry_point_count) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_avg_runtime) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_max_runtime) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_total_runtime) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_avg_cputime) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_max_cputime) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_runtime_gt_5s_count) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_runtime_gt_5s_percentage) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(apex_runtime_gt_10s_count) by (entry_point, quiddity)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apex exceptions occurred in last 1hr",
     "type": "stat",
     "description": "Refers to the errors that occur during the execution of Apex code",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (exception_category) (max_over_time(apex_exception_category_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Apex exceptions occurred in last 1hr",
     "type": "timeseries",
     "description": "Data categorized based on Types of exceptions occurred in last 1hr",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 262 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (exception_category) (max_over_time(apex_exception_category_count[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (exception_category) (count_over_time(apex_exception_details{exception_message=~\".*UNABLE_TO_LOCK_ROW.*\"}[5m]))",
       "legendFormat": "{{exception_category}} : RowLock"
      }
     ]
    },
    {
     "title": "Apex CPU Timeout exception details",
     "type": "table",
     "description": "Details displayed based on CPU Timeout exceptions occurred in last 1hr",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 276 },
     "targets": [
      {
       "expr": "count by (exception_category, exception_type, exception_message, stack_trace) (count_over_time(apex_exception_details{exception_message=~\".*Apex CPU time limit exceeded.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Apex Row Lock exception details",
     "type": "table",
     "description": "Details displayed based on Row Lock errors occurred in last 1hr",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 288 },
     "targets": [
      {
       "expr": "count by (exception_category, exception_type, exception_message, stack_trace) (count_over_time(apex_exception_details{exception_message=~\".*UNABLE_TO_LOCK_ROW.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Concurrent Apex Error request count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 300 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(concurrent_request_error_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Long Running Requests by Average Runtime with Runtime > 5sec",
     "type": "table",
     "description": "Top Long Running Requests by Average Runtime with Runtime > 5 seconds",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 303 },
     "targets": [
      {
       "expr": "max_over_time(most_apex_concurrent_errors_sorted_by_runtime[30m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Long Running Requests by Count with Runtime > 5sec",
     "type": "table",
     "description": "Top Long Running Requests by Count with Runtime > 5 seconds",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 312 },
     "targets": [
      {
       "expr": "max_over_time(most_apex_concurrent_errors_sorted_by_count[30m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}