{
 "title": "Salesforce Tech Debt Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last_login_date",
    "label": "Portal Users Last Login Date",
    "query": "2025 : ^2025.*,2024 : ^2024.*,2023 : ^2023.*,2022 : ^2022.*,2021 : ^2021.*,2020 : ^2020.*,Never : ^Never,Before 2020 : ^201.*"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: orange; text-align: center;\">\r\n    Salesforce Tech Debt Monitoring\r\n</h2>\r\n"
   }
  },
  {
   "title": "Health Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Salesforce Health Check Score %",
     "type": "stat",
     "description": "- 90% and above = Excellent\n- 80%–89% = Very Good\n- 70%–79% = Good\n- 55%–69% = Poor\n- 54% and below = Very Poor",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "security_health_check_score", "legendFormat": "{{grade}}" }
     ]
    },
    {
     "title": "Salesforce Health Check Trend",
     "type": "timeseries",
     "description": "- 90% and above = Excellent\n- 80%–89% = Very Good\n- 70%–79% = Good\n- 55%–69% = Poor\n- 54% and below = Very Poor",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "security_health_check_score", "legendFormat": "Health Check Score" }
     ]
    },
    {
     "title": "Salesforce Security Health Check Risks",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 149 },
     "targets": [
      { "expr": "salesforce_health_risks" }
     ]
    }
   ]
  },
  {
   "title": "Apex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apex Classes/Triggers API Version <=50.0",
     "type": "table",
     "description": "Apex classes & triggers developed by FTE in production running on API version 50.0 and older.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "deprecated_apex_classes\r\n" },
      { "expr": "deprecated_apex_triggers" }
     ]
    },
    {
     "title": "Percent of Apex Used",
     "type": "stat",
     "description": "Tracks the percentage of Apex code limit utilized, excluding comments and @isTest annotated classes, to monitor Salesforce's technical debt and ensure system scalability and compliance.\n\nLimit: 6 million characters",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apex_character_limit_percentage",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Custom Apex Length Without Comments",
     "type": "table",
     "description": "Displays Apex Classes and Apex Triggers by code length (excluding comments).\n\nSalesforce enforces a 6,000,000 character limit for Apex (excluding comments and @isTest classes).",
     "gridPos": { "h": 14, "w": 20, "x": 4, "y": 19 },
     "targets": [
      {
       "expr": "apex_class_length_without_comments"
      },
      {
       "expr": "apex_trigger_length_without_comments",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scheduled Apex Jobs",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
     "targets": [
      { "expr": "scheduled_apex_jobs" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dormant Salesforce Users",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 46 },
     "targets": [
      { "expr": "dormant_salesforce_users" }
     ]
    },
    {
     "title": "Dormant Portal Users - Last Login Date: $last_login_date",
     "type": "table",
     "description": "Set \"Portal Users Last Login Date\" variable to change this panel",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "dormant_portal_users{last_login_date=~\"$last_login_date\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Profiles & Permission Sets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Permission Sets with ≤10 Active Users",
     "type": "table",
     "description": "Permission sets developed by FTE in production with 10 or less active users.",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 47 },
     "targets": [
      { "expr": "unused_permissionsets\r\n" },
      { "expr": "limited_permissionsets", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Profiles with ≤5 Active Users",
     "type": "table",
     "description": "Profiles developed by FTE in production which are assigned to 5 or less active users.",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "five_or_less_profile_assignees\r\n"
      },
      { "expr": "unassigned_profiles", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Queues & Public Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Queues Per Object",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 48 },
     "targets": [
      { "expr": "total_queues_per_object" }
     ]
    },
    {
     "title": "Queues with No Members",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 48 },
     "targets": [
      { "expr": "queues_with_no_members" }
     ]
    },
    {
     "title": "Queues With Zero Open Cases",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 64 },
     "targets": [
      { "expr": "queues_with_zero_open_cases" }
     ]
    },
    {
     "title": "Public Groups With No Members",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 64 },
     "targets": [
      { "expr": "public_groups_with_no_members" }
     ]
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboards Running Under Inactive Users",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 81 },
     "targets": [
      { "expr": "dashboards_with_inactive_users" }
     ]
    }
   ]
  },
  {
   "title": "Workflow Rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Rules",
     "type": "table",
     "description": "Workflow rules developed by FTE in production.\n\nSalesforce has revealed that Workflow Rules and Process Builder will no longer be supported after December 31, 2025.",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1300 },
     "targets": [
      { "expr": "workflow_rules\r\n" }
     ]
    }
   ]
  }
 ]
}