scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ecs-services-file'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - /shared/ecs_file_sd.yml
